[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "JDHJdRCcBGBASx4Wn26h6MFqTbT8wLyjXAxwZoHS2dL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.30.0"
