[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
capstone_project = "HWJYZbkVaB3DxUnUE9RN3RCNKEoLK8ioiWfNpMAvu3Pb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
